kaist_player_node:
  ros__parameters:
    dataset_root: "/mnt/sata4t/datasets/kaist_complex_urban/extracted/urban30-gangnam"

    stereo_stamp_csv: "data/urban30-gangnam/sensor_data/stereo_stamp.csv"
    imu_csv: "data/urban30-gangnam/sensor_data/xsens_imu.csv"
    fog_csv: "data/urban30-gangnam/sensor_data/fog.csv"
    image_root: "img"

    imu_source: "fog_xsens"

    fog_use_dt_rate: true
    fog_scale: 1.0
    fog_axis_permutation: "0,1,2"
    fog_axis_signs: "1,1,1"
    fog_auto_bias: true
    fog_bias_estimation_duration_sec: 5.0

    left_keywords: "left,stereo_left,cam0"
    right_keywords: "right,stereo_right,cam1"

    left_topic: "/stereo/left/image_raw"
    right_topic: "/stereo/right/image_raw"
    imu_topic: "/imu/data_raw"
    clock_topic: "/clock"

    left_frame_id: "cam0"
    right_frame_id: "cam1"
    imu_frame_id: "imu"

    playback_rate: 1.0
    loop: false
    timer_period_sec: 0.002